// Generated by Dyad. Do not edit — Dyad regenerates this file.
//
// Lets a headed run drive the page already open in Dyad's preview panel
// instead of launching a separate browser, and isolates database data around
// each test case when Dyad supplies a test-case lifecycle endpoint.
import * as pw from "@playwright/test";
import { randomUUID } from "node:crypto";

export * from "@playwright/test";

const endpoint = process.env.DYAD_PREVIEW_CDP_ENDPOINT;
const cdpToken = process.env.DYAD_PREVIEW_CDP_TOKEN;
const caseEndpoint = process.env.DYAD_TEST_CASE_ENDPOINT;
const caseToken = process.env.DYAD_TEST_CASE_TOKEN;
const credentialKeys = [
  "DYAD_TEST_USER_EMAIL", "DYAD_TEST_USER_PASSWORD",
  "DYAD_TEST_SUPABASE_URL", "DYAD_TEST_SUPABASE_ANON_KEY",
];

async function caseRequest(phase: "before" | "after", id: string) {
  const response = await fetch(`${caseEndpoint}/${phase}/${id}`, {
    method: "POST",
    headers: { Authorization: `Bearer ${caseToken}` },
    signal: AbortSignal.timeout(190000),
  });
  if (!response.ok) throw new Error("Dyad couldn't prepare or clean up isolated test data.");
  return await response.json() as Record<string, string>;
}

const isolatedTest = !caseEndpoint ? pw.test : pw.test.extend<{ _dyadTestCase: void }>({
  _dyadTestCase: [async ({}, use) => {
    const id = randomUUID();
    for (const key of credentialKeys) delete process.env[key];
    try {
      const credentials = await caseRequest("before", id);
      for (const key of credentialKeys) {
        if (credentials[key]) process.env[key] = credentials[key];
      }
      await use();
    } finally {
      for (const key of credentialKeys) delete process.env[key];
      await caseRequest("after", id);
    }
  }, { auto: true, timeout: 220000 }],
});
// No browser is launched here, so the config's `launchOptions.slowMo` never
// applies — the connection carries it instead.
const slowMo = Number(process.env.DYAD_TEST_SLOW_MO) || 0;

function requireBaseUrl(): string {
  const baseUrl = process.env.DYAD_TEST_BASE_URL;
  if (!baseUrl) {
    throw new Error("Dyad preview: DYAD_TEST_BASE_URL is not set.");
  }
  return baseUrl;
}

function requirePreviewContext(browser: pw.Browser) {
  const contexts = browser.contexts();
  if (contexts.length !== 1) {
    throw new Error(
      `Dyad preview: the automation broker exposed ${contexts.length} browser contexts instead of exactly one.`,
    );
  }
  return contexts[0];
}

async function ensurePreviewBetterAuthSession({
  context,
  origin,
  requestUrl,
  requestData,
}: {
  context: pw.BrowserContext;
  origin: string;
  requestUrl: string;
  requestData: unknown;
}): Promise<void> {
  const page = context.pages().find((candidate) => {
    try {
      return new URL(candidate.url()).origin === origin;
    } catch {
      return false;
    }
  });
  if (!page) return;

  const result = await page.evaluate(
    async ({ signInUrl, data }) => {
      const hasSession = async () => {
        const response = await fetch("/api/auth/get-session", {
          credentials: "include",
        });
        if (!response.ok) return false;
        const body = await response.json().catch(() => null);
        return !!(
          body &&
          (body.user || (body.session && body.session.user))
        );
      };

      // A normal Playwright-owned context receives APIRequestContext cookies
      // automatically. Electron's pre-existing CDP context can report a
      // successful sign-in without exposing that cookie to the page. Avoid a
      // second request when the native session already has it.
      if (await hasSession()) return { ok: true, status: 200 };

      const response = await fetch(signInUrl, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        credentials: "include",
        body: typeof data === "string" ? data : JSON.stringify(data),
      });
      if (!response.ok) {
        return { ok: false, status: response.status };
      }
      return { ok: await hasSession(), status: response.status };
    },
    { signInUrl: requestUrl, data: requestData },
  );

  if (!result.ok) {
    throw new Error(
      `Dyad preview: Better Auth sign-in returned ${result.status}, but no browser session was established.`,
    );
  }
}

export const test = !endpoint
  ? isolatedTest
  : isolatedTest.extend({
      browser: [
        async ({}, use) => {
          if (!cdpToken) {
            throw new Error("Dyad preview: DYAD_PREVIEW_CDP_TOKEN is not set.");
          }
          const browser = await pw.chromium.connectOverCDP(endpoint, {
            slowMo,
            headers: { Authorization: `Bearer ${cdpToken}` },
          });
          try {
            await use(browser);
          } finally {
            // Disconnects this client; it never closes Dyad itself.
            await browser.close();
          }
        },
        { scope: "worker" },
      ],
      context: async ({ browser }, use) => {
        const baseUrl = requireBaseUrl();
        const origin = new URL(baseUrl).origin;
        // The broker is the security boundary: it must represent exactly the
        // isolated preview context and nothing from Dyad's privileged session.
        const context = requirePreviewContext(browser);
        // Playwright applies the config's `baseURL` when IT creates a context.
        // Dyad's preview created this one, so the option is missing and every
        // relative URL would have nothing to resolve against. The checks that
        // read it on the client — expect(page).toHaveURL("/x"),
        // page.waitForURL, route globs — are fixed by filling it in.
        // Best-effort: it's internal, so a rename should cost the extras, not
        // the run. Navigation and API requests resolve in Playwright's server
        // half instead, from the options the context was CREATED with, so they
        // are handled separately (below, and in the page fixture).
        const contextInternals = context as unknown as {
          _options?: { baseURL?: string };
        };
        if (contextInternals._options) {
          contextInternals._options.baseURL = baseUrl;
        }
        // context.request.get("/api/health") — and page.request, which is the
        // same object — would otherwise reach the server half as "/api/health"
        // and throw "Invalid URL", but only under a preview run. Resolve here
        // so a spec behaves the same whichever way Dyad runs it.
        type ApiCall = (url: unknown, options?: unknown) => unknown;
        const api = context.request as unknown as Record<string, ApiCall>;
        const originalApiMethods = new Map<string, ApiCall>();
        const apiMethodNames = ["fetch", "get", "post", "put", "patch", "delete", "head"];
        for (const name of apiMethodNames) {
          const original = api[name];
          if (typeof original !== "function") continue;
          originalApiMethods.set(name, original);
          // A Request object (fetch's other overload) carries its own URL.
          api[name] = async (url, options) => {
            const resolvedUrl =
              typeof url === "string" ? new URL(url, baseUrl).href : url;
            const response = await original.call(
              api,
              resolvedUrl,
              options,
            );

            // Better Auth depends on a first-party HttpOnly cookie. Playwright's
            // API client can return success under connectOverCDP while Electron's
            // native preview session remains signed out. Verify in the page and,
            // only when necessary, repeat this one idempotent credential exchange
            // through browser fetch so Chromium accepts Set-Cookie itself.
            if (typeof resolvedUrl === "string") {
              const parsedUrl = new URL(resolvedUrl);
              const requestData = (
                options as { data?: unknown } | undefined
              )?.data;
              if (
                name === "post" &&
                parsedUrl.origin === origin &&
                parsedUrl.pathname === "/api/auth/sign-in/email" &&
                requestData !== undefined &&
                response &&
                typeof (response as { ok?: unknown }).ok === "function" &&
                (response as { ok: () => boolean }).ok()
              ) {
                await ensurePreviewBetterAuthSession({
                  context,
                  origin,
                  requestUrl: resolvedUrl,
                  requestData,
                });
              }
            }

            return response;
          };
        }
        try {
          // Pre-existing context: hand it over without closing it afterwards.
          await use(context);
        } finally {
          // It outlives this fixture, so the patches have to come back off.
          for (const [name, original] of originalApiMethods) {
            api[name] = original;
          }
        }
      },
      page: async ({ context }, use, testInfo) => {
        const baseUrl = requireBaseUrl();
        const origin = new URL(baseUrl).origin;
        const page = context.pages().find((candidate) => {
          try {
            return new URL(candidate.url()).origin === origin;
          } catch {
            return false;
          }
        });
        if (!page) {
          throw new Error(
            `Dyad preview: no page serving ${origin} — is the preview panel showing this app?`,
          );
        }
        // page.goto resolves relative URLs in Playwright's server half, from
        // the options the context was CREATED with — out of reach of the
        // assignment above, so "/" would reach Chromium verbatim and fail as an
        // invalid URL. Resolve it here instead. Absolute URLs pass through
        // untouched, and the original is restored so the page we hand back to
        // the user is the one we borrowed.
        const originalGoto = page.goto;
        page.goto = (url, options) =>
          originalGoto.call(page, new URL(url, baseUrl).href, options);
        try {
          // Pre-existing page: leave it open for Dyad to replace after this
          // single-test process finishes.
          await use(page);
        } finally {
          page.goto = originalGoto;
          // Playwright's built-in screenshot/trace recorder is off for preview
          // runs (see the config) because tracing needs browser-global CDP
          // commands the preview-only broker rejects. Attach the selected page
          // directly instead. It lands
          // first because auto fixtures tear down last, so it is the one
          // Dyad picks up even in an app whose config predates that change.
          if (testInfo.status !== testInfo.expectedStatus) {
            try {
              await testInfo.attach("screenshot", {
                body: await page.screenshot(),
                contentType: "image/png",
              });
            } catch {
              // A screenshot is a nicety; never fail teardown over it.
            }
          }
        }
      },
    });

export const expect = pw.expect;
