// Generated by Dyad. Only active in a Dyad test runner.
const dns = require("node:dns");
const { syncBuiltinESMExports } = require("node:module");
let hostname;
try {
  const url = new URL(process.env.DYAD_TEST_BASE_URL);
  if (url.protocol === "http:" && url.port && !url.username && !url.password &&
      /^app-([1-9][0-9]*)\.localhost$/.test(url.hostname) &&
      Number.isSafeInteger(Number(url.hostname.split(".")[0].slice(4)))) hostname = url.hostname;
} catch {}
if (hostname) {
  const lookup = dns.lookup;
  const lookupPromise = dns.promises.lookup;
  // Delegate even the local lookup to Node so family/all overloads and error
  // behavior stay identical. No URL rewriting: cookie/Host semantics survive.
  dns.lookup = function(host, ...args) {
    return lookup.call(this, host === hostname ? "127.0.0.1" : host, ...args);
  };
  dns.promises.lookup = function(host, ...args) {
    return lookupPromise.call(this, host === hostname ? "127.0.0.1" : host, ...args);
  };
  syncBuiltinESMExports();
}
