#!/bin/bash

# Chore Champ - Cloudflare Pages Dev Environment Setup
# Requires: Cloudflare CLI installed (npm install -g wrangler)
# Requires: Cloudflare API token with Pages permissions

set -e

echo "🚀 Chore Champ - Cloudflare Dev Environment Setup"
echo "================================================="
echo ""

# Check if wrangler is installed
if ! command -v wrangler &> /dev/null; then
    echo "❌ Wrangler not found. Installing..."
    npm install -g wrangler
fi

echo "✅ Wrangler installed"
echo ""

# Read API token from environment
if [ -z "$CF_API_TOKEN" ]; then
    echo "❌ CF_API_TOKEN not set"
    echo ""
    echo "Please set your Cloudflare API token:"
    echo "   export CF_API_TOKEN='your-api-token-here'"
    echo ""
    echo "Or create a file .cloudflare-token:"
    echo "   echo 'your-api-token-here' > .cloudflare-token"
    echo "   export CF_API_TOKEN=$(cat .cloudflare-token)"
    exit 1
fi

# Read account ID from environment
if [ -z "$CF_ACCOUNT_ID" ]; then
    echo "❌ CF_ACCOUNT_ID not set"
    echo ""
    echo "Please set your Cloudflare Account ID:"
    echo "   export CF_ACCOUNT_ID='your-account-id-here'"
    exit 1
fi

# Read project name
PROJECT_NAME="${1:-chore-champ}"
echo "📦 Project: $PROJECT_NAME"
echo ""

# Step 1: Create dev branch
echo "📦 Creating dev branch..."
wrangler pages branch create "$PROJECT_NAME" dev --account-id "$CF_ACCOUNT_ID"

# Step 2: Create test branch
echo "📦 Creating test branch..."
wrangler pages branch create "$PROJECT_NAME" test --account-id "$CF_ACCOUNT_ID"

# Step 3: Configure branch deployments
echo "📦 Configuring branch deployments..."

# Create wrangler.toml for Pages if it doesn't exist
if [ ! -f "wrangler-pages.toml" ]; then
    cat > wrangler-pages.toml << 'EOF'
[vars]
IS_DEV = "true"
IS_PRODUCTION = "false"
CF_PAGES_BUILD = "true"
EOF
    echo "✅ Created wrangler-pages.toml"
fi

# Update wrangler-pages.toml with branch-specific configs
cat > wrangler-pages.toml << EOF
# Chore Champ - Cloudflare Pages Configuration
# Auto-generated by setup script

[vars]
IS_DEV = "true"
IS_PRODUCTION = "false"
CF_PAGES_BUILD = "true"

# Branch-specific deployments
[[branch_deployments]]
branch = "main"
production_branch = ""

[[branch_deployments]]
branch = "dev"
production_branch = "dev"

[[branch_deployments]]
branch = "test"
production_branch = "test"
EOF

echo "✅ Configured wrangler-pages.toml"
echo ""

# Step 4: Create environment variables file
echo "📦 Creating environment variables template..."
cat > .env.cloudflare << 'EOF'
# Cloudflare Pages Environment Variables
# Add these to your Cloudflare Pages dashboard after setup

# Production (main branch)
# DATABASE_URL=postgresql://user:password@host:port/chore_champ
# CLOUDFLARE_ACCESS_URL=https://access.your-domain.com
# CLOUDFLARE_ACCESS_CLIENT_ID=your-client-id
# CLOUDFLARE_ACCESS_CLIENT_SECRET=your-client-secret
# GEMINI_API_KEY=your-api-key

# Dev/Test branches (leave blank for local mode)
# DATABASE_URL=
# CLOUDFLARE_ACCESS_URL=
# CLOUDFLARE_ACCESS_CLIENT_ID=
# CLOUDFLARE_ACCESS_CLIENT_SECRET=
# GEMINI_API_KEY=
EOF

echo "✅ Created .env.cloudflare template"
echo ""

echo "================================================="
echo "✅ Cloudflare Dev Environment Setup Complete!"
echo "================================================="
echo ""
echo "📋 Next Steps:"
echo ""
echo "1. Verify branches were created:"
echo "   wrangler pages branch list --project-name $PROJECT_NAME --account-id $CF_ACCOUNT_ID"
echo ""
echo "2. Configure branch deployments in Cloudflare Dashboard:"
echo "   - Go to: https://dash.cloudflare.com/profile/accounts/*/pages/projects/$PROJECT_NAME"
echo "   - Settings → Branches"
echo "   - Add branch configurations (see wrangler-pages.toml)"
echo ""
echo "3. Set up environment variables:"
echo "   - Copy .env.cloudflare to Cloudflare Pages dashboard"
echo "   - Add variables for main branch (production)"
echo "   - Leave dev/test branches blank (local mode)"
echo ""
echo "4. Test your dev environment:"
echo "   git checkout dev"
echo "   git push origin dev"
echo "   Visit: https://dev.$PROJECT_NAME.pages.dev"
echo ""
echo "================================================="
echo "📚 Documentation:"
echo "   docs/CLOUDFLARE-DEV-SETUP.md"
echo "   docs/CLOUDFLARE-QUICK-START.md"
echo "================================================="
echo ""
